name: build oc.nginx

on:
  repository_dispatch:
    types: dispatch-from-webModules
  push:
    branches:
      - main
      
jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  
  build:
    runs-on: ubuntu-latest
    env: 
      imagetag: ${{ github.head_ref || github.ref_name || 'dev' }}
    outputs:
      output1: ${{ steps.imagename.outputs.image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
 
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_TOKEN }}
         
      - name: "image tag"
        run: echo "image tag set to '${{ env.imagetag }}'"

      - name: Build and push builder image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.builder
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          build-args: |
            BASE_IMAGE_RELEASE=22.04
            BASE_IMAGE=ubuntu
          tags: |
            abcdesktopio/oc.nginx:builder

      - name: Build and push oc.nginx:${{ env.imagetag }}
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          context: .
          platforms: linux/amd64, linux/arm64
          build-args: |
            BASE_IMAGE_RELEASE=jammy
            BASE_IMAGE=openresty/openresty
          push: true
          tags: |
            abcdesktopio/oc.nginx:${{ env.imagetag }}
            
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: docker.io/abcdesktopio/oc.nginx:${{ env.imagetag }}
          format: 'sarif'
          output: 'oc-nginx-trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'oc-nginx-trivy-results.sarif'
      
      - name: Output image name
        id: imagename 
        run: echo "::set-output name=image::abcdesktopio/oc.nginx:${{ env.imagetag }}"
