name: Update oc.nginx

on:
  repository_dispatch:
    types: dispatch-from-webModules
  push:
    branches:
      - main

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: oc.nginx
  DOCKERFILE_NAME: oc.nginx

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  build:

    runs-on: self-hosted

    steps:
      - name: Clone sources
        run: |
          rm -rf ..?* .[!.]* *
          git -c http.extraheader="Authorization: basic ${{ secrets.TOKEN }}" clone "https://github.com/${{ secrets.USER_NAME }}/oc.nginx.git" .
          git -c http.extraheader="Authorization: basic ${{ secrets.TOKEN }}" submodule update --init --recursive --remote

      - name: Login to registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build image
        run: docker build . --file $DOCKERFILE_NAME --no-cache --tag ${{ secrets.DOCKER_REPOSITORY }}:$IMAGE_NAME

      - name: Push image then remove it
        run: |
          docker push ${{ secrets.DOCKER_REPOSITORY }}:$IMAGE_NAME
          docker rmi ${{ secrets.DOCKER_REPOSITORY }}:$IMAGE_NAME
